/*
 * Ratings Microservice
 *
 * A service to store and retrieve product ratings.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;

namespace RatingApi.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class SystemApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This operation can be used as a liveness probe to verify that the server is alive</remarks>
        /// <response code="204">The service is available</response>
        /// <response code="500"></response>
        [HttpGet]
        [Route("/healthz")]
        [SwaggerOperation("LivenessProbe")]
        public virtual IActionResult LivenessProbe()
        {
             return StatusCode(204);
        }
    }
}
