/*
 * Books Microservice
 *
 * A service to store books and request data about them.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// A book from the database
    /// </summary>
    [DataContract]
    public partial class Book
    {
        /// <summary>
        /// The id of the book
        /// </summary>
        /// <value>The id of the book</value>
        [Required]
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public int Id { get; set; }

        /// <summary>
        /// The title of the book
        /// </summary>
        /// <value>The title of the book</value>
        [Required]
        [DataMember(Name="title", EmitDefaultValue=false)]
        [MaxLength(20)]
        public string Title { get; set; } = string.Empty;

    }
}
