/*
 * Products Microservice
 *
 * A service to post and get product data
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
//using Products.Api.Converters;

namespace Products.Api.Models
{ 
    /// <summary>
    /// Product data with its id
    /// </summary>
    [DataContract]
    public partial class ProductWithIdDto : IEquatable<ProductWithIdDto>
    {
        /// <summary>
        /// id of the profuct
        /// </summary>
        /// <value>id of the profuct</value>
        [DataMember(Name="productId", EmitDefaultValue=true)]
        public int ProductId { get; set; }

        /// <summary>
        /// Gets or Sets Product
        /// </summary>
        [DataMember(Name="product", EmitDefaultValue=false)]
        public ProductDto Product { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductWithIdDto {\n");
            sb.Append("  ProductId: ").Append(ProductId).Append("\n");
            sb.Append("  Product: ").Append(Product).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProductWithIdDto)obj);
        }

        /// <summary>
        /// Returns true if ProductWithIdDto instances are equal
        /// </summary>
        /// <param name="other">Instance of ProductWithIdDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductWithIdDto other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ProductId == other.ProductId ||
                    
                    ProductId.Equals(other.ProductId)
                ) && 
                (
                    Product == other.Product ||
                    Product != null &&
                    Product.Equals(other.Product)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + ProductId.GetHashCode();
                    if (Product != null)
                    hashCode = hashCode * 59 + Product.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProductWithIdDto left, ProductWithIdDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProductWithIdDto left, ProductWithIdDto right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
