// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewAPI.DbContexts;

#nullable disable

namespace ReviewAPI.Migrations
{
    [DbContext(typeof(ReviewContext))]
    [Migration("20230914123011_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.21");

            modelBuilder.Entity("ReviewAPI.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductReview")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReviewId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            ProductId = 420,
                            ProductReview = "Overall good value for its price, but the battery life leaves much to be desired",
                            UserId = 15
                        },
                        new
                        {
                            ReviewId = 2,
                            ProductId = 69,
                            ProductReview = "Very bad money grab",
                            UserId = 26
                        },
                        new
                        {
                            ReviewId = 3,
                            ProductId = 76,
                            ProductReview = "Actually perfect, I can't recommend it enough",
                            UserId = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
